spring:
  datasource:
    url: jdbc:h2:mem:blogs
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
