spring:
  datasource:
    url: jdbc:h2:mem:blogs
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
# options for processing exploration
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  graphql:
#    graphiql:
#      enabled: true
